language: rust
rust:
- stable
cache: cargo
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake || true; fi
- cargo build --verbose --all
- cargo test --verbose --all
matrix:
  allow_failures:
  - os: linux
os:
- osx
- linux
addons:
  apt:
    packages:
      - libgtk-3-dev
before_deploy:
  - brew install node || true
  - npm install --global create-dmg
  - ./scripts/release_build.sh
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dzUBk53mtIp4tB1AK5jMM4pFY2hUZcU5drNhwQL3hIPJkRRLSWhxzUUbbS4fsIhU+5HjDeeSOblit9fIRKEWtuCM0L/PVZaeA/PkpCToDrkJhU3NpOe59COuI/oP+CLc4T8pDFiHMHY3ZPRUaIIAp/eL4ETTwtwGZ0uGkg9yzEI=
  file:
    - ./dist/LoLUpdater.dmg
    - ./dist/lolupdater-cli.tar.bz2
  on:
    repo: MOBASuite/LoLUpdater-macOS
    rust: stable
    os: osx
    tags: true
