language: rust
rust:
- stable
- nightly
script:
- cargo build --verbose --all
- cargo test --verbose --all
matrix:
  allow_failures:
  - rust: nightly
  - os: linux
os:
- linux
- osx
addons:
  apt:
    packages:
    - libgtk-3-dev
before-deploy:
  - brew install node
  - npm install --global create-dmg
  - ./scripts/build.sh
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dzUBk53mtIp4tB1AK5jMM4pFY2hUZcU5drNhwQL3hIPJkRRLSWhxzUUbbS4fsIhU+5HjDeeSOblit9fIRKEWtuCM0L/PVZaeA/PkpCToDrkJhU3NpOe59COuI/oP+CLc4T8pDFiHMHY3ZPRUaIIAp/eL4ETTwtwGZ0uGkg9yzEI=
  file:
    - ./dist/LoLUpdater.dmg
    - ./dist/lolupdater-cli.tar.gz
  on:
    repo: LoLUpdater/LoLUpdater-macOS
    rust: stable
    os: osx
