[package]
name = "lolupdater"
version = "3.0.1"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]

[profile.release]
lto = true

[target.'cfg(macos)'.dependencies]
hyper = { version = "0.9", default-features = false, features = ["security-framework"] }

[target.'not(cfg(macos))'.dependencies]
hyper = "0.9"

[dependencies]
flate2 = "0.2"
lazy_static = "0.2"
regex = "0.1"
ring = "0.5"
tar = { version = "0.4", default-features = false }
tempdir = "0.3"
walkdir = "1"
