[package]
name = "lolupdater-cli"
version = "5.0.2"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]

[dependencies.lolupdater-core]
path = "../lolupdater-core"

[dependencies]
clap = "2.26.2"
error-chain = "0.11.0"
env_logger = "0.4.3"
log = "0.3.8"
